version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  mariadb:
    driver: ${VOLUMES_DRIVER}

services:

### Workspace Utilities ##################################
    workspace:
      image: repetitor202/laradock-boston_workspace:220129-xdebug2
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ./php-worker/supervisord.d:/etc/supervisord.d
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      networks:
        - backend

### PHP-FPM ##############################################
    php-fpm:
      image: repetitor202/laradock-boston_php-fpm:211022-xdebug2
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      ports:
        - "${PHP_FPM_XDEBUG_PORT}:9003"
#      expose:
#        - "9000"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      depends_on:
        - workspace
      networks:
        - backend

#### PHP Worker ############################################
#    php-worker:
#      build:
#        context: ./php-worker
#        args:
#          - CHANGE_SOURCE=${CHANGE_SOURCE}
#          - LARADOCK_PHP_VERSION=${PHP_VERSION}
#          - PHALCON_VERSION=${PHALCON_VERSION}
#          - INSTALL_BZ2=${PHP_WORKER_INSTALL_BZ2}
#          - INSTALL_GD=${PHP_WORKER_INSTALL_GD}
#          - INSTALL_IMAGEMAGICK=${PHP_WORKER_INSTALL_IMAGEMAGICK}
#          - INSTALL_GMP=${PHP_WORKER_INSTALL_GMP}
#          - INSTALL_GNUPG=${PHP_WORKER_INSTALL_GNUPG}
#          - INSTALL_LDAP=${PHP_WORKER_INSTALL_LDAP}
#          - INSTALL_PGSQL=${PHP_WORKER_INSTALL_PGSQL}
#          - INSTALL_MONGO=${PHP_WORKER_INSTALL_MONGO}
#          - INSTALL_BCMATH=${PHP_WORKER_INSTALL_BCMATH}
#          - INSTALL_MEMCACHED=${PHP_WORKER_INSTALL_MEMCACHED}
#          - INSTALL_OCI8=${PHP_WORKER_INSTALL_OCI8}
#          - INSTALL_MSSQL=${PHP_WORKER_INSTALL_MSSQL}
#          - INSTALL_PHALCON=${PHP_WORKER_INSTALL_PHALCON}
#          - INSTALL_XLSWRITER=${PHP_WORKER_INSTALL_XLSWRITER}
#          - INSTALL_SOAP=${PHP_WORKER_INSTALL_SOAP}
#          - INSTALL_ZIP_ARCHIVE=${PHP_WORKER_INSTALL_ZIP_ARCHIVE}
#          - INSTALL_MYSQL_CLIENT=${PHP_WORKER_INSTALL_MYSQL_CLIENT}
#          - INSTALL_AMQP=${PHP_WORKER_INSTALL_AMQP}
#          - INSTALL_CASSANDRA=${PHP_WORKER_INSTALL_CASSANDRA}
#          - INSTALL_GEARMAN=${PHP_WORKER_INSTALL_GEARMAN}
#          - INSTALL_GHOSTSCRIPT=${PHP_WORKER_INSTALL_GHOSTSCRIPT}
#          - INSTALL_SWOOLE=${PHP_WORKER_INSTALL_SWOOLE}
#          - INSTALL_TAINT=${PHP_WORKER_INSTALL_TAINT}
#          - INSTALL_FFMPEG=${PHP_WORKER_INSTALL_FFMPEG}
#          - INSTALL_AUDIOWAVEFORM=${PHP_WORKER_INSTALL_AUDIOWAVEFORM}
#          - INSTALL_REDIS=${PHP_WORKER_INSTALL_REDIS}
#          - INSTALL_IMAP=${PHP_WORKER_INSTALL_IMAP}
#          - INSTALL_XMLRPC=${PHP_WORKER_INSTALL_XMLRPC}
#          - INSTALL_SSDB=${PHP_WORKER_INSTALL_SSDB}
#          - PUID=${PHP_WORKER_PUID}
#          - PGID=${PHP_WORKER_PGID}
#          - IMAGEMAGICK_VERSION=${PHP_WORKER_IMAGEMAGICK_VERSION}
#      volumes:
#        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
#        - ./php-worker/supervisord.d:/etc/supervisord.d
#      depends_on:
#        - workspace
#      networks:
#        - backend

### NGINX Server #########################################
    nginx:
      image: repetitor202/laradock-boston_nginx:220216
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
#        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
#        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - backend

### MariaDB ##############################################
    mariadb:
      image: repetitor202/laradock-boston_mariadb:220216
      volumes:
        - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
        - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MARIADB_PORT}:3306"
      environment:
#        - TZ=${WORKSPACE_TIMEZONE}
        - MYSQL_DATABASE=${MARIADB_DATABASE}
        - MYSQL_USER=${MARIADB_USER}
        - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      networks:
        - backend
